# Generated by Django 5.1.1 on 2024-10-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customers_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='otp',
            field=models.CharField(default='546345', max_length=255),
        ),
    ]
