# Generated by Django 5.1.1 on 2024-11-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequests',
            name='request_id',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False),
        ),
    ]
